### ISSUE TITLE
could anyone set this up on google colab?

### ISSUE THREAD

**Issue by GeorvityLabs** [wpeebles/gangealing#1]
Would be awesome to try out this project on google colab?

Also, would this kind of inference be possible on device (say on a mediatek dimensity 1200 chip ? )

**Comment by wpeebles** [comment]
Thanks for the interest! I'm looking into creating a Colab notebook to run some of the models on video.

Regarding your second question, I don't have a good answer as I'm not very familiar with current on-device chips for DL inference. That said, I don't think inference with our Spatial Transformers is particularly expensive relative to other ResNet-based nets. To give some frame of reference, on one RTX 6000 GPU we can do offline single-object tracking of video frames with our LSUN Cats Spatial Transformer model at ~15fps (including rendering the visualization).

**Comment by GeorvityLabs** [comment]
Yup, It would awesome to run inference on recorded frames from the front/rear facing camera.

Definitely looking forward to the colab notebook!

**Comment by duskvirkus** [comment]
@wpeebles Got a colab notebook partly working but I got a cuda out of memory when I tried to vis_correspondence script. Was on a V100 with 16gb. What's the minimum required vram?

**Comment by duskvirkus** [comment]
Got it working with only one image in the grid. I'll share the notebook once I do some clean up.

**Comment by wpeebles** [comment]
Great, thanks for working on it! `vis_correspondence.py` is currently one of the more memory-intensive scripts. Depending on where the out-of-memory error occurs, it may be fixable by decreasing the `--splat_batch` argument.

**Comment by GeorvityLabs** [comment]
@duskvirkus that's good to hear!
Def looking forward to your notebook.

**Comment by duskvirkus** [comment]
Did some basic clean up and comments. Might not get around to working on it more for a few days so here's a version. https://github.com/duskvirkus/colab-notebooks/blob/main/gangealing/gangealing_colab_vis_correspondence.ipynb

Pretty basic mostly getting around using conda tried using colabconda but really doesn't play well with python 3.8. Was going to add more than the `vis_correspondence.py` but just haven't gotten around to it. I'll try to remember update the github version if I add more.

cc @GeorvityLabs

**Comment by GeorvityLabs** [comment]
Awesome , thanks for the notebook @duskvirkus 
Def looking forward to any updates down the line.

**Comment by wpeebles** [comment]
Thanks @duskvirkus! To make things less of a pain, I'll try to cache small versions of LSUN that people can download to get started more quickly, and I'll probably set-up a Colab for the video stuff specifically. I'll hopefully get around to it before this weekend.

**Comment by GeorvityLabs** [comment]
that's awesome @wpeebles , def looking forward to the Colab! :)

**Comment by wpeebles** [comment]
I created a [Colab notebook here](https://colab.research.google.com/drive/1JkUjhTjR8MyLxwarJjqnh836BICfocTu) for running mixed reality with GANgealing. It supports uploading your own video to use (or you can use one of ours provided in the notebook). Have fun!

**Comment by GeorvityLabs** [comment]
awesome colab @wpeebles , just tried it out!
