### ISSUE TITLE
loss is always 0 && "transformed_sample_0******.png" become one-color and only 6kb after 105000 iters

### ISSUE THREAD

**Issue by adaxigua** [wpeebles/gangealing#10]
question one: on training, the loss is always 0
question two: "transformed_sample_0******.png" become one-color and only 6kb after 105000 iters, 

why did I fail to train the model? 
Thanks!

------------------------------------------------------------------------------------------------------------
I didn't change the code. The weights was auto download.

**script**:
~~~
CUDA_VISIBLE_DEVICES=7 python train.py \
--ckpt cat --load_G_only --padding_mode border --vis_every 5000 --ckpt_every 50000 \
--iter 1500000 --tv_weight 1000 --loss_fn vgg_ssl --exp-name debug
~~~

**out**:
~~~
Setting up [baseline] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading VGG with pretrained=False
Loaded custom VGG weights.
Loading model from cat
Only G_EMA has been loaded from checkpoint. Other nets are random!
Fitting PCA...
Learning Rate Cycles: [149999, 187499, 262499, 412499, 712499, 1312499]
perceptual loss: 0.1561; tv loss: 0.000000; identity loss: 0.0000; psi: 1.0000:
~~~

**Comment by wpeebles** [comment]
Hi @wangherr. The `--batch` training argument controls the per-GPU batch size, so training on one GPU in your command will default to a total batch size of 5 (this is the default value for `--batch`). The unimodal GANgealing models we reported in our paper and released were trained with 8 GPUs for a total batch size of 40. I suspect a batch size of 5 could cause stability issues. Could you try retraining over more GPUs or increase your batch size? It is maybe also possible decreasing the `--ll_lr` argument to `0.001` or lower could help stabilize training with small batch sizes, although this is just a guess as I have not personally tried doing this before.

It is normal for `tv loss` and `identity loss` to be equal to 0 early in training when `psi` is much greater than 0, but it is not normal for `perceptual loss` to go to 0. Is this what you observed?

I will also try to reproduce the problem you're observing this weekend. Would you mind sharing the `sample.png`, `truncated_sample.png` and `transformed_sample.png` files for the latest step in training as well as early in training? Thanks!

**Comment by adaxigua** [comment]
sample_1500000：👇
![sample_1500000](https://user-images.githubusercontent.com/68674487/162335170-d5479157-0a88-46fb-9957-f40738eee6cd.png)


----------------------------------------------------------------------------
transformed_sample_1500000:👇

![transformed_sample_1500000](https://user-images.githubusercontent.com/68674487/162334506-0bf0dea6-f420-4c9d-a867-2b472885cd6f.png)

--------------------------------------------------------------------------

truncated_sample_1500000：👇
![truncated_sample_1500000](https://user-images.githubusercontent.com/68674487/162334691-7d8d5e5f-84ae-492d-b785-7b152ccebf24.png)
------------------------------------------------------------------------------------------

**Comment by adaxigua** [comment]
transformed_sample_0000000：👇
![transformed_sample_0000000](https://user-images.githubusercontent.com/68674487/162335282-fb5cde35-9e5c-4662-8c23-136c3f052da9.png)

--------------------------------------------------------------------------------------------------------------

transformed_sample_0100000：👇
![transformed_sample_0100000](https://user-images.githubusercontent.com/68674487/162335344-ea73abfa-bcca-49c2-b69b-11171fe57049.png)

-----------------------------------------------------------------------------------------------------------------------------------

transformed_sample_0105000：👇
![transformed_sample_0105000](https://user-images.githubusercontent.com/68674487/162335375-2b074aa6-8512-4933-b53d-0f6ecc3a4edf.png)

---------------------------------------------------------------------------------------------------------------------------------

transformed_sample_1500000：👇
![transformed_sample_1500000](https://user-images.githubusercontent.com/68674487/162335410-bcd35dde-a355-4760-80c1-3a936b5fd32f.png)

**Comment by adaxigua** [comment]
> Hi @wangherr. The `--batch` training argument controls the per-GPU batch size, so training on one GPU in your command will default to a total batch size of 5 (this is the default value for `--batch`). The unimodal GANgealing models we reported in our paper and released were trained with 8 GPUs for a total batch size of 40. I suspect a batch size of 5 could cause stability issues. Could you try retraining over more GPUs or increase your batch size? It is maybe also possible decreasing the `--ll_lr` argument to `0.001` or lower could help stabilize training with small batch sizes, although this is just a guess as I have not personally tried doing this before.
> 
> It is normal for `tv loss` and `identity loss` to be equal to 0 early in training when `psi` is much greater than 0, but it is not normal for `perceptual loss` to go to 0. Is this what you observed?
> 
> I will also try to reproduce the problem you're observing this weekend. Would you mind sharing the `sample.png`, `truncated_sample.png` and `transformed_sample.png` files for the latest step in training as well as early in training? Thanks!

Thanks, I will try to follow your advices. If needed，I could share the other files.

**Comment by wpeebles** [comment]
Thanks for the files @wangherr! After seeing the truncated samples, I am not sure decreasing `ll_lr` will help with small batch sizes. I've started a training job to reproduce the issue.

For some context, I ran the `lsun_cats_lpips.sh` training script soon after I released the codebase to verify training was correct, and I got good results. This is why I suspect the issue is batch size-related, although I will investigate further if this does not solve the problem.

**Comment by nikky4D** [comment]
For single gpu training, what would you advice would be a good change to see good results if we don't decrease `ll_lr`. I'm using one gpu and would like to modifiy this for a small batch size run.

**Comment by wpeebles** [comment]
Hi @wangherr. Using a bigger batch size indeed appears to fix the problem. I was able to reproduce the failure case you saw when training with your single GPU command (total batch size = 5). My run seemed to collapse just before 100,000 steps. I then trained on 4x GPUs with `--batch 10` (total batch size = 40) and the results at 150,000 steps look reasonable to me. Note that we trained our released unimodal models for just over 1.3M gradient steps, so results should continue to get better than this relatively early point in training. I've attached some results below.

@nikky4D For those who can't use a large batch size, the safest recommendation is to use gradient accumulation. For example, if you can only use a batch size of 5 on 1 GPU, you would put a for-loop that iterates 8 times around computation of the loss and the `full_stn_loss.backward()` call. Once you exit this for-loop, you would step the two optimizers. This should give similar results to larger batch training, although it will be slower. I've included a quick (untested) snippet below that might be a good starting point.

I did also try using LPIPS with a total batch size of 5 (only changes to @wangherr training command were `--loss_fn lpips --tv_weight 2500`). It didn't collapse like `--loss_fn vgg_ssl` did, but the results are very noticeably worse than the total batch size 40 version after 200,000 steps.  This is also consistent with some findings I had during development of GANgealing where small batch sizes seemed to give worse results than larger ones.

Thank you guys for testing the training code!

---
Gradient accumulation code snippet (untested, should replace lines 105 through 134 in `train.py`):
```
stn.zero_grad()
ll.zero_grad()
for gradient_accumulation_step in range(8):
    if args.clustering or args.flips:  # Clustering-specific perceptual loss:
        perceptual_loss, delta_flow = gangealing_cluster_loss(generator, stn, ll, loss_fn, resize_fake2stn, psi,
                                                              args.batch, args.dim_latent, args.freeze_ll,
                                                              args.num_heads, args.flips, device,
                                                              sample_from_full_res=args.sample_from_full_res,
                                                              padding_mode=args.padding_mode)
    else:  # Standard GANgealing perceptual loss (unimodal):
        perceptual_loss, delta_flow = gangealing_loss(generator, stn, ll, loss_fn, resize_fake2stn, psi,
                                                      args.batch, args.dim_latent, args.freeze_ll, device,
                                                      sample_from_full_res=args.sample_from_full_res,
                                                      padding_mode=args.padding_mode)
    tv_loss = total_variation_loss(delta_flow) if args.tv_weight > 0 else zero
    flow_idty_loss = flow_identity_loss(delta_flow) if args.flow_identity_weight > 0 else zero

    loss_dict = {"p": perceptual_loss, "tv": tv_loss, "f": flow_idty_loss}

    full_stn_loss = perceptual_loss + args.tv_weight * tv_loss + args.flow_identity_weight * flow_idty_loss
    full_stn_loss.div(8).backward()
t_optim.step()
if not args.freeze_ll:
    ll_optim.step()
if psi_is_fixed:  # Step learning rate schedulers once psi has been fully-annealed to zero:
    epoch = max(0, (i - args.anneal_psi) / args.period)
    t_sched.step(epoch)
    ll_sched.step(epoch)

accumulate(t_ema, t_module, accum)
```
---
Early training results (150,000 gradient steps) for total batch size = 40 `vgg_ssl` model:

Samples (STN Inputs):
![sample_0150000](https://user-images.githubusercontent.com/35885960/162527375-e3129c73-c930-4a3f-a1f7-dd44db7945f9.png)

Truncated Samples (STN Targets):
![truncated_sample_0150000](https://user-images.githubusercontent.com/35885960/162527418-01c339ce-b8ad-4449-9756-12e4a7e54724.png)

Transformed Samples (STN Output, iters=1):
![transformed_sample_0150000](https://user-images.githubusercontent.com/35885960/162527452-46d7961f-fda9-4690-bac4-856e1a8e2183.png)

**Comment by wpeebles** [comment]
I've let the total batch size = 40 `vgg_ssl` model train to 300,000 steps, and its PCK numbers (which measure quality of predicted correspondence) are approaching the numbers we obtained after 1.3M steps that we reported in the paper. So I think everything should be good with the training code as long as a sufficient batch size is used. Thanks again for trying it out!

**Comment by adaxigua** [comment]
Thanks for anwser. I got the wanted result by used 4 gpus and set batch 10 per gpu. As for 1 gpu and batch 40，it was out of memory. 

By the way, have you tried the method on small size dataset, such as cifar10(h*w: 32*32)?

**Comment by wpeebles** [comment]
The lowest resolution I've tried is 128x128, but I think running at lower resolutions should be possible too (I guess the images might need to be upsampled before being fed into the perceptual loss during training). We haven't tested the method on multi-class datasets like CIFAR, though.
