### ISSUE TITLE
About PCK-transfer

### ISSUE THREAD

**Issue by BenfenYU** [wpeebles/gangealing#14]
Hello, thanks for your excellent work!
![image](https://user-images.githubusercontent.com/33017944/163806871-4f43cb54-43c4-4976-a51b-7e271d3effca.png)
![image](https://user-images.githubusercontent.com/33017944/163807215-85a07c08-5dee-48c5-a917-edd6781bff43.png)

As shown in the figure, the position of keypoints in image B  is random (depends on the SPair dataset). However, your model will transform input image(here is image A) to a modification of average image (almost the front). So, how do your calculate the PCK between gt image B and the transformed image?

**Comment by wpeebles** [comment]
Hi @BenfenYU. Our Spatial Transformers have two operations that are used for transferring keypoints:

`congeal_points`: Determines where points in the input image lie in the congealed (aligned) image.
`uncongeal_points`: The inverse of `congeal_points`. Determines where points in the congealed image lie in the input image. 

Say we have a pair of images A and B, and A has ground truth keypoints kpsA. So to transfer keypoints, we first compute `kpsA_congealed = congeal_points(A, kpsA)` which will map A's keypoints to congealed space. Then, we run `kpsB = uncongeal_points(B, kpsA_congealed)` which will map the congealed keypoints to image B. Here is a figure from our paper to illustrate this (we also go into more explicit detail about how the `congeal_points` and `uncongeal_points` work under-the-hood in Supplementary B.7). 

<img width="712" alt="Screen Shot 2022-04-18 at 3 45 53 PM" src="https://user-images.githubusercontent.com/35885960/163889160-1c7171fe-33fb-4264-b7a2-e2352fe852aa.png">

A limitation of our method is that it can only accurately propagate keypoints that are visible in the congealed space (so, based on the average image for LSUN Cats, it will only work for keypoints on the front of a cat's body). For example, in the pair of cat images you included, our pre-trained STN checkpoint would do a poor job transferring the paw keypoints.

Feel free to let me know if you have more questions or need additional clarification!

**Comment by BenfenYU** [comment]
Thanks for your answer! I have understood.
