### ISSUE TITLE
Can we build and run in win10? _splat cpp extension

### ISSUE THREAD

**Issue by vicdxxx** [wpeebles/gangealing#15]

**Comment by wpeebles** [comment]
Hi @vicdxxx. I don't have any experience using CUDA on Windows, so the short answer is I'm not sure 😅. That said, there's nothing I am aware of in the splat extension that is platform-specific, so it may work out-of-the-box with Windows as long as you have CUDA.

**Comment by vicdxxx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
