### ISSUE TITLE
Can this method serve as an optical flow estimator?

### ISSUE THREAD

**Issue by linjing7** [wpeebles/gangealing#17]
Hi, your work is really cool. I wonder can it serve as an optical flow estimator? If yes, could you please show me the demo code? By the way, what are its advantages and disadvantages when compared with the conventional optical flow networks, e.g., PWCNet ?

**Comment by wpeebles** [comment]
Hi @linjing7, sorry for the delay in responding! The short answer is that yes, GANgealing can serve as an optical flow estimator. Long answer:

GANgealing tackles a more general version of the optical flow problem than RAFT/PWCNet/etc. The latter methods are usually only able to reliably find flows when the appearance of objects is relatively constant across time, and when object/camera motion is relatively smooth. In contrast, GANgealing addresses the "generalized" optical flow problem, where the goal is to find correspondences within an object category even in the presence of significant appearance variation or large sudden changes in the camera/object pose.

The upside of our our method is that it can find correspondences (pixel flows) even when there are sudden changes in appearance/camera. For example, our method can find an accurate pixel flow field between two images of completely different cat breeds in completely different poses, whereas my expectation would be that RAFT and low-level optical flow methods would completely fail. But, the downside is that we can only reliably find flows for semantic features present in our learned template. For example, although we can do a good job tracking a cat's upper body, if you instead wanted to know how pixels in the background of a video are moving, I imagine RAFT or PWCNet would perform notably better.

You can use `mixed_reality.py` to find pixel flows for an input video (docs [here](https://github.com/wpeebles/gangealing#mixed-reality-object-lenses-)). It tracks the location of pixels specified via a user's input mask of the learned template. You can visualize the predicted flow field with that script. To save the flows, you'd need to modify the script to save the `propagated_points` variable at about line 190 in the code.

Feel free to follow-up if anything wasn't clear!

**Comment by linjing7** [comment]
Hi, thank you very much for your detailed reply! I will have a try.

**Comment by wpeebles** [comment]
I'll go ahead and close this, but feel free to re-open/make a new issue if you have more questions!
