### ISSUE TITLE
RuntimeError in colab

### ISSUE THREAD

**Issue by amrzv** [wpeebles/gangealing#29]
Hi.
There is a `RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'` when running colab notebook:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/36787333/187750964-b96d2589-1121-4f32-b4d8-f940e1070e30.png">

[Solution](https://stackoverflow.com/a/55969838): add imageio==2.4.1 to dependencies or add `!pip install imageio==2.4.1` to Setup cell.

**Comment by wpeebles** [comment]
Thanks! I updated the colab notebook and also our conda environment files to specify the dependency. Let me know if you still encounter any issues.

**Comment by amrzv** [comment]
Thanks for fixing it!
