### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by QWERDF007** [wpeebles/gangealing#3]
`python applications/vis_correspondence.py --ckpt cat --real_data_path data/lsun_cats --vis_in_stages --real_size 512 --output_resolution 512 --resolution 512 --label_path assets/masks/cat_mask.png --dset_indices 1922 2363 8558 7401 9750 7432 2105 53 1946`

> Traceback (most recent call last):
>   File "applications/vis_correspondence.py", line 22, in <module>
>     from datasets import MultiResolutionDataset, img_dataloader
> ModuleNotFoundError: No module named 'datasets'

**Comment by shinya7y** [comment]
A possible solution is https://github.com/shinya7y/gangealing/commit/d5c785c453bad292925cd26ced883c29f9038503 , though it's somewhat ugly.

**Comment by wpeebles** [comment]
Adding the project to your PYTHONPATH should solve the issue (let me know if it doesn't). For example:

```bash
cd gangealing
export PYTHONPATH="${PYTHONPATH}:${PWD}"
```
I'd be in favor of an automated solution like the one @shinya7y proposed, although I'm also not a big fan of sticking the `sys.path.insert`s in multiple files.

**Comment by QWERDF007** [comment]
> 

thanks, it works.
