### ISSUE TITLE
how to train LPIPS(Perceptual Losses) myself

### ISSUE THREAD

**Issue by adaxigua** [wpeebles/gangealing#30]
if I want to train the LPIPS(Perceptual Losses) myself, where could I found the paper？

is this project: https://github.com/richzhang/PerceptualSimilarity

Thanks！

**Comment by wpeebles** [comment]
Yeah, that's the repo for LPIPS. For our self-supervised perceptual loss, we trained VGG networks using SimCLR [in this repo ](https://github.com/facebookresearch/vissl)(we had to implement the VGG architecture in it ourselves though).
