### ISSUE TITLE
Missing State Dict Keys for CelebA

### ISSUE THREAD

**Issue by codyreading** [wpeebles/gangealing#32]
Hi again @wpeebles!

Looks like there is difference between the state_dict of the Generator and the pretrained weights for CelebA. Specifically:
```
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "convs.10.conv.weight", "convs.10.conv.blur.kernel", "convs.10.conv.modulation.weight", "convs.10.conv.modulation.bias", "convs.10.noise.weight", "convs.10.activate.bias", "convs.11.conv.weight", "convs.11.conv.modulation.weight", "convs.11.conv.modulation.bias", "convs.11.noise.weight", "convs.11.activate.bias", "to_rgbs.5.bias", "to_rgbs.5.upsample.kernel", "to_rgbs.5.conv.weight", "to_rgbs.5.conv.modulation.weight", "to_rgbs.5.conv.modulation.bias", "noises.noise_11", "noises.noise_12".
```

Looks like the generator has more `StyledConv` blocks and `ToRGB` blocks than the pretrained weights. Not sure which is supposed to be the correct configuration.

Command that I'm running:
```
bash scripts/training/celeba.sh 
```

Thanks for the help :)

**Comment by codyreading** [comment]
Apologies, I just needed to set the `--gen_size 128` command. I've added a PR if you would like to merge this fix.
https://github.com/wpeebles/gangealing/pull/33

**Comment by wpeebles** [comment]
Thanks for catching the issue!
