### ISSUE TITLE
can't load CUB dataset

### ISSUE THREAD

**Issue by MichalGeyer** [wpeebles/gangealing#34]
I tried to run the script for CUB data preparation - 
python prepare_data.py --cub_acsm --out data/cub_val --size 256

I'm getting:

 FileNotFoundError: [Errno 2] No such file or directory: 'data/val_cub_cleaned_new.mat'

How can I download this file?

**Comment by wpeebles** [comment]
Hi @MichalGeyer. I just pushed a change which I think should fix the issue. Could you try updating the repo and let me know if the error goes away?

**Comment by MichalGeyer** [comment]
work now, thanks!
