### ISSUE TITLE
Resolution support  

### ISSUE THREAD

**Issue by TimmmYang** [wpeebles/gangealing#7]
Hi, I tried videos with size 16:9 (1280*720) and results is cropped with size 1:1, can I keep the original size of the result video?

**Comment by wpeebles** [comment]
Sorry for the delay in response @TimmmYang! The newest version of the repo now supports preserving the aspect ratio.

If you're using this repo manually, delete the LMDB you previously created and then call `prepare_data.py` using `--pad resize_small_side` in your command. Then you should be good to go.

If you're using the Colab notebook, you can re-upload your video and it should maintain input aspect ratio by default now.
